name: weather_pipeline
version: "1.0.0"
config-version: 2

profile: weather_pipeline

model-paths: ["models"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

models:
  weather_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
